/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetoSlugRouteImport } from './routes/projeto.$slug'
import { Route as VideoSlugRouteImport } from './routes/video.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoSlugRoute = ProjetoSlugRouteImport.update({
  id: '/projeto/$slug',
  path: '/projeto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoSlugRoute = VideoSlugRouteImport.update({
  id: '/video/$slug',
  path: '/video/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/video/$slug': typeof VideoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/video/$slug': typeof VideoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/video/$slug': typeof VideoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projeto/$slug' | '/video/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projeto/$slug' | '/video/$slug'
  id: '__root__' | '/' | '/projeto/$slug' | '/video/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjetoSlugRoute: typeof ProjetoSlugRoute
  VideoSlugRoute: typeof VideoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto/$slug': {
      id: '/projeto/$slug'
      path: '/projeto/$slug'
      fullPath: '/projeto/$slug'
      preLoaderRoute: typeof ProjetoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$slug': {
      id: '/video/$slug'
      path: '/video/$slug'
      fullPath: '/video/$slug'
      preLoaderRoute: typeof VideoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjetoSlugRoute: ProjetoSlugRoute,
  VideoSlugRoute: VideoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
